import type { SpreadReadingTemplate } from "./types";

const commonForbiddenPatterns = [
  "不要把解读写成逐张牌流水账。",
  "不要替用户或对方做绝对决定。",
  "不要使用必然、一定、命中注定等绝对预言。",
  "不要堆砌元素、星象、数字术语；只有能解释结构时才使用。",
  "不要输出 Markdown 分隔线、项目符号清单或表格。",
  "不要在正文里写“组合意义是”“组合意义中”“资料显示”“结构分析笔记显示”等暴露提示词的表达。",
  "不要原文引用牌组组合资料；组合资料只可转化为牌间联动视角。",
];

const defaultTemplate: SpreadReadingTemplate = {
  slug: "default",
  purpose: "用通用结构看清问题主线、关键矛盾、现实映射和可执行下一步。",
  sections: [
    "1. 一句话结论",
    "2. 牌阵结构",
    "3. 关键矛盾",
    "4. 现实映射",
    "5. 风险提醒",
    "6. 行动建议",
    "7. 观察指标",
  ],
  instruction: "先整合整副牌的结构，再解释关键牌位；输出要像成熟占卜师的个案笔记，而不是牌义百科。",
  positionWeights: {},
  timeScope: {
    defaultWindow: "未来 1-4 周",
    observationWindow: "未来 1-2 周",
    note: "通用牌阵只给观察窗口，不做绝对日期判断。",
  },
  positionRules: [
    "先判断牌阵中最承重的位置，再把其他牌作为支撑、抵消或补充。",
    "每个判断都要能回指到牌位、牌名、正逆位或用户问题。",
  ],
  relationRules: [
    "优先解释同花色重复、大阿卡纳集中、逆位集中、宫廷牌人物感和数字阶段感。",
    "支持关系用于说明资源和可推进部分，抵消关系用于说明矛盾和风险。",
  ],
  forbiddenPatterns: commonForbiddenPatterns,
  length: { min: 1100, max: 1600 },
  maxTokens: 3000,
};

const templates: Record<string, SpreadReadingTemplate> = {
  "single-guidance": {
    slug: "single-guidance",
    purpose: "把一张牌压缩成当下最需要看见的提醒和一个具体动作。",
    sections: ["1. 一句话结论", "2. 牌面线索", "3. 当前提醒", "4. 今日行动", "5. 观察指标"],
    instruction: "单张牌不展开复杂因果，只提炼核心主题、现实落点和一个可执行动作。",
    positionWeights: { 1: { weight: "primary", role: "核心讯息" } },
    timeScope: {
      defaultWindow: "当天到 3 天",
      observationWindow: "今天或未来 3 天",
      note: "单张建议牌适合当下 check-in，不适合承担重大决策终局。",
    },
    positionRules: ["第 1 张就是核心讯息，重点看正逆位如何改变行动方式。"],
    relationRules: ["单张牌没有牌间关系，不要硬写组合意义；可使用大阿卡纳/花色/数字作为辅助线索。"],
    forbiddenPatterns: [...commonForbiddenPatterns, "不要写成多牌阵式的复杂报告。"],
    length: { min: 700, max: 1000 },
    maxTokens: 2200,
  },
  "three-card": {
    slug: "three-card",
    purpose: "用三张牌看背景、现状与走向，或转换成问题、阻碍与建议。",
    sections: ["1. 一句话结论", "2. 三张牌的阶段变化", "3. 当前关键矛盾", "4. 现实映射", "5. 行动建议", "6. 观察指标"],
    instruction: "三张牌必须写出阶段感，不要只并列解释三张牌。",
    positionWeights: {
      1: { weight: "secondary", role: "背景/过去影响" },
      2: { weight: "primary", role: "当下状态" },
      3: { weight: "secondary", role: "近期走向" },
    },
    timeScope: {
      defaultWindow: "未来 1-4 周",
      observationWindow: "未来 1-2 周",
      note: "三张牌阵适合快速阶段诊断，优先看过程变化而非最终结局。",
    },
    positionRules: [
      "第 1 张说明形成当前局面的背景。",
      "第 2 张说明当下最真实的状态，是解读重心。",
      "第 3 张只表达趋势和可调整方向，不写绝对结果。",
    ],
    relationRules: ["比较第 1 到第 3 张的数字、花色、正逆位变化，判断是推进、停滞还是回收。"],
    forbiddenPatterns: commonForbiddenPatterns,
    length: { min: 1000, max: 1400 },
    maxTokens: 2800,
  },
  "career-five": {
    slug: "career-five",
    purpose: "围绕事业问题整合现状、阻碍、优势、近期发展和行动建议。",
    sections: ["1. 一句话结论", "2. 事业结构", "3. 关键卡点", "4. 可用优势", "5. 近期发展", "6. 行动建议", "7. 观察指标"],
    instruction: "事业牌阵要把阻碍、优势和近期发展连成一条现实路径。",
    positionWeights: {
      1: { weight: "secondary", role: "当前事业处境" },
      2: { weight: "primary", role: "主要阻碍" },
      3: { weight: "primary", role: "可调动资源" },
      4: { weight: "secondary", role: "近期发展" },
      5: { weight: "primary", role: "行动建议" },
    },
    timeScope: {
      defaultWindow: "未来 2-6 周",
      observationWindow: "未来 1-2 周",
      note: "事业五张看短中期推进，对项目议题可放宽到 2 个月。",
    },
    positionRules: [
      "第 1 张说明当前职业状态。",
      "第 2 张是主要阻碍，优先解释。",
      "第 3 张是可调动资源，不要写成结果。",
      "第 4 张只描述近期趋势。",
      "第 5 张必须落到具体行动。",
    ],
    relationRules: [
      "比较第 2 张阻碍与第 3 张优势，看资源能否化解卡点。",
      "比较第 4 张趋势与第 5 张建议，看行动是否顺势。",
    ],
    forbiddenPatterns: commonForbiddenPatterns,
    length: { min: 1200, max: 1600 },
    maxTokens: 3000,
  },
  "cross-five": {
    slug: "cross-five",
    purpose: "用十字结构看问题核心、背景、当下、未来和阻碍/帮助。",
    sections: ["1. 一句话结论", "2. 核心结构", "3. 背景如何影响现在", "4. 未来趋势", "5. 阻碍或帮助", "6. 行动建议", "7. 观察指标"],
    instruction: "五牌十字阵要围绕中心牌组织，不要把四周牌平铺。",
    positionWeights: {
      1: { weight: "primary", role: "问题核心" },
      2: { weight: "secondary", role: "过去影响" },
      3: { weight: "secondary", role: "当前处境" },
      4: { weight: "secondary", role: "近期趋势" },
      5: { weight: "primary", role: "阻碍或帮助" },
    },
    timeScope: {
      defaultWindow: "未来 2-8 周",
      observationWindow: "未来 1-2 周",
      note: "五牌十字适合单一议题的根因与近期走向，不把趋势位当终局。",
    },
    positionRules: [
      "第 1 张是全局核心。",
      "第 2、3 张解释过去到现在的承接。",
      "第 4 张是趋势，不是宿命结果。",
      "第 5 张要判断更像阻碍还是帮助，并给出依据。",
    ],
    relationRules: ["中心牌与四周牌的支持/抵消关系优先于单牌关键词。"],
    forbiddenPatterns: commonForbiddenPatterns,
    length: { min: 1100, max: 1500 },
    maxTokens: 2900,
  },
  "relationship-six": {
    slug: "relationship-six",
    purpose: "看双方状态、互动结构、边界/误解以及修复路径。",
    sections: ["1. 一句话结论", "2. 关系结构", "3. 双方状态", "4. 关键误解或边界", "5. 修复路径", "6. 行动建议", "7. 观察指标"],
    instruction: "关系牌阵重点是互动结构，不替任何一方做绝对心理判决。",
    positionWeights: {
      1: { weight: "primary", role: "用户在关系中的状态" },
      2: { weight: "primary", role: "对方呈现方式" },
      3: { weight: "primary", role: "关系现状" },
      4: { weight: "primary", role: "互动阻碍" },
      5: { weight: "secondary", role: "近期关系趋势" },
      6: { weight: "primary", role: "沟通或边界建议" },
    },
    timeScope: {
      defaultWindow: "未来 4-8 周",
      observationWindow: "未来 1-2 周",
      note: "关系六张重点看互动是否有可观察变化，不替对方内心下结论。",
    },
    positionRules: [
      "重点比较第 1 张和第 2 张的差异。",
      "第 3 张代表关系本身，不等于任何一方的想法。",
      "第 4 张是互动卡点。",
      "第 5 张是近期趋势，不做绝对承诺。",
      "第 6 张必须转化为沟通或边界建议。",
    ],
    relationRules: [
      "如果第 1、2 张花色或正逆位冲突，优先解释双方节奏错位。",
      "第 4 张与第 6 张的关系决定修复路径是否现实。",
    ],
    forbiddenPatterns: [...commonForbiddenPatterns, "不要断言对方一定爱或不爱。"],
    length: { min: 1200, max: 1700 },
    maxTokens: 3200,
  },
  "lovers-pyramid": {
    slug: "lovers-pyramid",
    purpose: "用四张牌拆开你、对方、关系本身和近期发展。",
    sections: ["1. 一句话结论", "2. 关系结构", "3. 你与对方的差异", "4. 关系本身", "5. 近期发展", "6. 行动建议", "7. 观察指标"],
    instruction: "恋人金字塔要比较双方位置，再由关系位和发展位给出趋势。",
    positionWeights: {
      1: { weight: "secondary", role: "用户在关系中的状态" },
      2: { weight: "secondary", role: "对方呈现方式" },
      3: { weight: "primary", role: "关系结构" },
      4: { weight: "secondary", role: "近期发展" },
    },
    timeScope: {
      defaultWindow: "未来 1-3 个月",
      observationWindow: "未来 1-2 周",
      note: "当前实现为四张恋人金字塔，重点看双方差异与关系位承接。",
    },
    positionRules: [
      "第 1 张是用户在关系中的状态。",
      "第 2 张是对方呈现方式，必须克制表达。",
      "第 3 张代表关系结构。",
      "第 4 张是近期发展或结果提醒。",
    ],
    relationRules: ["第 1、2 张的差异是主线，第 3、4 张用于判断连接是否可被现实推进。"],
    forbiddenPatterns: [...commonForbiddenPatterns, "不要把对方位写成读心术。"],
    length: { min: 1100, max: 1500 },
    maxTokens: 3000,
  },
  "path-of-choice": {
    slug: "path-of-choice",
    purpose: "比较 A/B 两条路径的机会、代价、隐藏变量与决策前动作。",
    sections: ["1. 一句话结论", "2. 两个选择的本质差异", "3. 路径 A 的机会与代价", "4. 路径 B 的机会与代价", "5. 隐藏变量", "6. 决策前动作", "7. 观察指标"],
    instruction: "选择牌阵必须成对比较，不替用户做决定，而是澄清代价、条件和验证信号；每个路径只写机会与代价，不展开成长篇单牌解释。",
    positionWeights: {
      1: { weight: "secondary", role: "路径 A 现状" },
      2: { weight: "secondary", role: "路径 A 结果倾向" },
      3: { weight: "secondary", role: "路径 B 现状" },
      4: { weight: "secondary", role: "路径 B 结果倾向" },
      5: { weight: "primary", role: "隐藏变量" },
      6: { weight: "primary", role: "决策前动作" },
      7: { weight: "primary", role: "整体倾向" },
    },
    timeScope: {
      defaultWindow: "决策前 1-6 周",
      observationWindow: "未来 1-2 周",
      note: "选择之路负责验证条件与比较代价，不替用户拍板。",
    },
    positionRules: [
      "必须成对比较 A 现状/A 结果 与 B 现状/B 结果。",
      "第 5 张隐藏变量优先级高。",
      "第 6 张给决策前动作。",
      "第 7 张只做整体倾向总结。",
      "路径 A 和路径 B 每节最多两段：第一段写机会，第二段写代价。",
      "隐藏变量、决策前动作、观察指标必须保留，不能被前文挤掉。",
      "如果用户问题涉及裸辞、辞职、分手、搬家、借钱、投资、创业等高风险现实决策，第 6 节必须写决策前安全垫：资源/现金流、时间线、替代方案、止损点。",
      "高风险决策中不得只按牌面倾向鼓励用户马上行动；必须把不可逆代价和验证条件说清楚。",
      "观察指标默认写未来 1-2 周内可验证的信号。",
    ],
    relationRules: [
      "A 路径内部看第 1 与第 2 张是否一致。",
      "B 路径内部看第 3 与第 4 张是否一致。",
      "再比较 A/B 哪边代价更高、哪边更可落地。",
    ],
    forbiddenPatterns: [
      ...commonForbiddenPatterns,
      "不要直接说选 A 或选 B 是唯一正确答案。",
      "不要在 A/B 路径里逐张复述所有组合意义。",
      "不要省略“决策前动作”和“观察指标”。",
      "不要擅自把新方向具体化为创业公司、大公司、某个岗位或某个行业，除非用户原问题明确写出。",
    ],
    length: { min: 1300, max: 1700 },
    maxTokens: 3800,
  },
  "self-state": {
    slug: "self-state",
    purpose: "把自我状态外化为压力、需求、被忽略的部分和调整方向。",
    sections: ["1. 一句话结论", "2. 当前心理结构", "3. 压力源", "4. 被忽略的需求", "5. 调整方向", "6. 行动建议", "7. 观察指标"],
    instruction: "自我状态牌阵要温和、具体，不给用户贴负面标签。",
    positionWeights: {
      1: { weight: "secondary", role: "外在呈现" },
      2: { weight: "secondary", role: "内在感受" },
      3: { weight: "primary", role: "压力源" },
      4: { weight: "primary", role: "被忽略的需求" },
      5: { weight: "primary", role: "调节方向" },
    },
    timeScope: {
      defaultWindow: "现在到未来 7 天",
      observationWindow: "未来 3-7 天",
      note: "自我状态牌阵看当下调节，不给用户贴人格或疾病标签。",
    },
    positionRules: [
      "第 1 张看外在呈现。",
      "第 2 张看内在感受。",
      "第 3 张是压力源。",
      "第 4 张是需要被看见的需求。",
      "第 5 张必须落到调整方向。",
    ],
    relationRules: ["比较外在状态与内在情绪的差异，判断用户是在外显、压抑还是过度承担。"],
    forbiddenPatterns: [...commonForbiddenPatterns, "不要诊断心理疾病或给用户贴人格标签。"],
    length: { min: 1100, max: 1600 },
    maxTokens: 3000,
  },
  "celtic-cross": {
    slug: "celtic-cross",
    purpose: "整合核心张力、内外因素、短期变化、希望担心与长期趋势。",
    sections: ["1. 一句话结论", "2. 核心张力", "3. 内外因素", "4. 过去如何影响现在", "5. 短期变化", "6. 希望与担心", "7. 长期趋势", "8. 行动建议", "9. 观察指标"],
    instruction: "凯尔特十字要做整合式深读，不能逐张平铺十张牌。",
    positionWeights: {
      1: { weight: "primary", role: "现状" },
      2: { weight: "primary", role: "挑战" },
      3: { weight: "secondary", role: "过去影响" },
      4: { weight: "secondary", role: "意识目标" },
      5: { weight: "primary", role: "无意识根因" },
      6: { weight: "secondary", role: "近未来" },
      7: { weight: "primary", role: "个人态度/建议入口" },
      8: { weight: "secondary", role: "外部影响" },
      9: { weight: "secondary", role: "希望与担忧" },
      10: { weight: "secondary", role: "投射结果/长期趋势" },
    },
    timeScope: {
      defaultWindow: "数周到 3 个月",
      observationWindow: "未来 2-6 周",
      note: "凯尔特十字适合复杂阶段议题，结果位只是趋势投射，不是宿命终局。",
    },
    positionRules: [
      "第 1 和第 2 张组成核心冲突。",
      "第 3、5 张看潜意识和远因。",
      "第 4、6 张看目标与短期变化。",
      "第 7、8 张比较个人态度和环境因素。",
      "第 9 张解释期待与焦虑。",
      "第 10 张只表达趋势，不写宿命结果。",
    ],
    relationRules: [
      "核心冲突优先级最高，其次是个人态度与环境因素是否同向。",
      "短期变化和最终趋势若冲突，必须说明中间条件。",
    ],
    forbiddenPatterns: commonForbiddenPatterns,
    length: { min: 1500, max: 2100 },
    maxTokens: 4200,
  },
};

export function getSpreadReadingTemplate(slug: string | undefined | null): SpreadReadingTemplate {
  if (!slug) return defaultTemplate;
  return templates[slug] ?? defaultTemplate;
}

export type { SpreadReadingTemplate } from "./types";
