import { minorArcana } from "@/content/minor-arcana";
import type { TarotCard } from "@/lib/tarot/types";
import { slugify } from "@/lib/utils";

type MajorSeed = Omit<TarotCard, "slug" | "imageUrl">;

const majorArcanaSeeds: MajorSeed[] = [
  {
    id: "major-0-fool",
    nameZh: "愚者",
    nameEn: "The Fool",
    arcana: "major",
    suit: null,
    number: 0,
    keywordsUpright: ["启程", "信任", "轻盈", "冒险"],
    keywordsReversed: ["莽撞", "逃避现实", "轻率", "失焦"],
    meaningUpright: "愚者象征新的旅程开始，提醒你以开放心态迎向未知，但不是盲目，而是相信自己能在路上学习。",
    meaningReversed: "逆位愚者提示你可能想靠冲动摆脱现状，却没有真正看清风险，也可能因害怕失误而迟迟不肯启程。",
    loveMeaning: "感情里它代表新鲜感、重新认识彼此，或一段不按旧规则发展的关系。",
    careerMeaning: "工作上它常指转职、跨界、创业或新的尝试，需要勇气也需要基本准备。",
  },
  {
    id: "major-1-magician",
    nameZh: "魔术师",
    nameEn: "The Magician",
    arcana: "major",
    suit: null,
    number: 1,
    keywordsUpright: ["执行力", "资源整合", "表达", "主导"],
    keywordsReversed: ["操控", "空转", "过度包装", "分心"],
    meaningUpright: "魔术师代表把想法落成现实的能力，你手里已经有足够资源，关键在于聚焦与行动。",
    meaningReversed: "逆位时容易出现说得漂亮但落地不足，或为了掌控结果而过度操盘的倾向。",
    loveMeaning: "关系里它提示主动沟通与明确表达，也提醒留意过度话术。",
    careerMeaning: "事业上有利于提案、谈判、启动新项目，靠技能与表达拿结果。",
  },
  {
    id: "major-2-high-priestess",
    nameZh: "女祭司",
    nameEn: "The High Priestess",
    arcana: "major",
    suit: null,
    number: 2,
    keywordsUpright: ["直觉", "内在知识", "静观", "保留"],
    keywordsReversed: ["压抑感受", "讯号混乱", "疏离", "误判"],
    meaningUpright: "女祭司提醒你暂停外求，把注意力转向直觉与细微信号。眼下答案未必在表面，而在沉静里显现。",
    meaningReversed: "逆位可能表示你明明感到不对，却被外界噪音带偏，也可能因过度封闭而错失信息。",
    loveMeaning: "感情里它常与暧昧、未说出口的情绪或需要更多观察的阶段有关。",
    careerMeaning: "工作上适合调研、蓄力和策略思考，不宜被催促下仓促表态。",
  },
  {
    id: "major-3-empress",
    nameZh: "皇后",
    nameEn: "The Empress",
    arcana: "major",
    suit: null,
    number: 3,
    keywordsUpright: ["滋养", "丰盛", "吸引力", "创造"],
    keywordsReversed: ["过度付出", "放纵", "依赖", "匮乏感"],
    meaningUpright: "皇后带来滋养与丰盛，象征关系、资源或创意正在成长，重点是接纳和稳定培育。",
    meaningReversed: "逆位时可能是照顾别人太多、忽略自己，也可能以物质或情绪补偿来掩盖内在匮乏。",
    loveMeaning: "在关系里代表被爱、被接住，以及温柔而真实的连结。",
    careerMeaning: "事业上有利于创意产出、个人品牌、女性消费与审美相关领域。",
  },
  {
    id: "major-4-emperor",
    nameZh: "皇帝",
    nameEn: "The Emperor",
    arcana: "major",
    suit: null,
    number: 4,
    keywordsUpright: ["秩序", "责任", "边界", "掌控"],
    keywordsReversed: ["僵化", "控制欲", "压迫", "失序"],
    meaningUpright: "皇帝要求你建立结构、规则与边界，让局势回到可管理状态。",
    meaningReversed: "逆位提醒你可能把稳定误当成控制，或因为逃避责任导致局面更乱。",
    loveMeaning: "感情里它提示承诺、责任与关系规则，也可能出现强势一方。",
    careerMeaning: "工作上适合做制度、管理、预算与长期规划。",
  },
  {
    id: "major-5-hierophant",
    nameZh: "教皇",
    nameEn: "The Hierophant",
    arcana: "major",
    suit: null,
    number: 5,
    keywordsUpright: ["传统", "学习", "信念", "导师"],
    keywordsReversed: ["教条", "形式主义", "反叛", "失去认同"],
    meaningUpright: "教皇象征从经验、传统或可靠系统中获得支持，提醒你回到基本原则。",
    meaningReversed: "逆位表示你可能在旧规则里感到窒息，或为了反对而反对，尚未建立自己的价值体系。",
    loveMeaning: "感情里它可能对应正式关系、现实承诺或价值观磨合。",
    careerMeaning: "事业上有利于培训、考试、认证、制度型组织与专业成长。",
  },
  {
    id: "major-6-lovers",
    nameZh: "恋人",
    nameEn: "The Lovers",
    arcana: "major",
    suit: null,
    number: 6,
    keywordsUpright: ["连结", "选择", "价值一致", "坦诚"],
    keywordsReversed: ["分裂", "犹豫", "价值冲突", "关系失衡"],
    meaningUpright: "恋人牌强调关系与选择。真正的重点不是浪漫，而是你是否愿意对自己的选择负责。",
    meaningReversed: "逆位意味着关系或决定里存在不一致，可能想同时保留多种可能，却因此失去方向。",
    loveMeaning: "这是强烈的情感连结牌，也常提示需要坦白面对彼此真实需求。",
    careerMeaning: "工作上多与合作、签约、双选题和价值 alignment 有关。",
  },
  {
    id: "major-7-chariot",
    nameZh: "战车",
    nameEn: "The Chariot",
    arcana: "major",
    suit: null,
    number: 7,
    keywordsUpright: ["推进", "意志", "掌舵", "胜利"],
    keywordsReversed: ["失控", "硬推", "方向偏移", "拉扯"],
    meaningUpright: "战车要求你把分散的力量整合起来，明确方向并持续前进。",
    meaningReversed: "逆位时常见外在看似在冲，内在其实各拉各的，导致效率低且疲惫。",
    loveMeaning: "关系里它说明双方需要明确目标，不然只会陷入谁主导谁的角力。",
    careerMeaning: "事业上利于抢进度、拿结果、打硬仗，但要避免透支。",
  },
  {
    id: "major-8-strength",
    nameZh: "力量",
    nameEn: "Strength",
    arcana: "major",
    suit: null,
    number: 8,
    keywordsUpright: ["稳定内核", "温柔掌控", "耐心", "勇气"],
    keywordsReversed: ["自我怀疑", "压抑情绪", "逞强", "耗损"],
    meaningUpright: "力量不是硬碰硬，而是以柔软和稳定去承接强烈情绪与现实压力。",
    meaningReversed: "逆位提示你可能外表撑着，内在却已消耗过度，或压抑愤怒与脆弱导致反弹。",
    loveMeaning: "感情里它是成熟关系的象征，强调包容、耐心和稳定支持。",
    careerMeaning: "工作上意味着用持续性、情绪稳定与韧性赢得局面。",
  },
  {
    id: "major-9-hermit",
    nameZh: "隐士",
    nameEn: "The Hermit",
    arcana: "major",
    suit: null,
    number: 9,
    keywordsUpright: ["独处", "整理", "深思", "寻找答案"],
    keywordsReversed: ["封闭", "逃避互动", "孤立", "停滞"],
    meaningUpright: "隐士提醒你抽离杂音，回到真正属于自己的判断。慢下来不是倒退，而是整顿方向。",
    meaningReversed: "逆位时容易把疗愈变成躲避，或因过度封闭而错失外界帮助。",
    loveMeaning: "关系里可能是需要空间、重新思考，或双方节奏不同。",
    careerMeaning: "工作上适合复盘、研究、独立深挖，不适合盲目追求表面热闹。",
  },
  {
    id: "major-10-wheel-of-fortune",
    nameZh: "命运之轮",
    nameEn: "Wheel of Fortune",
    arcana: "major",
    suit: null,
    number: 10,
    keywordsUpright: ["转折", "时机", "周期", "变化"],
    keywordsReversed: ["失控感", "抗拒变化", "重复课题", "时机不稳"],
    meaningUpright: "命运之轮预示节奏转换，提醒你顺势而为，抓住变化里的窗口期。",
    meaningReversed: "逆位说明你可能被变化推着走，或在同样模式里打转，尚未意识到循环根源。",
    loveMeaning: "感情里有机会迎来关系转折，也意味着需要顺应阶段变化。",
    careerMeaning: "事业上常见于市场变化、岗位调整、机会窗口出现。",
  },
  {
    id: "major-11-justice",
    nameZh: "正义",
    nameEn: "Justice",
    arcana: "major",
    suit: null,
    number: 11,
    keywordsUpright: ["平衡", "事实", "责任", "结果对应"],
    keywordsReversed: ["偏见", "失衡", "逃责", "判断失准"],
    meaningUpright: "正义要求回到事实、选择与后果的对应关系。它强调清晰、诚实和边界。",
    meaningReversed: "逆位代表你可能只看见对自己有利的片段，或想逃避应承担的结果。",
    loveMeaning: "关系里需要公平沟通、坦白与现实评估，避免情绪替代事实。",
    careerMeaning: "工作上关联合约、评估、绩效、规则与长期公正。",
  },
  {
    id: "major-12-hanged-man",
    nameZh: "倒吊人",
    nameEn: "The Hanged Man",
    arcana: "major",
    suit: null,
    number: 12,
    keywordsUpright: ["暂停", "换视角", "让渡", "等待成熟"],
    keywordsReversed: ["无效等待", "自我牺牲", "卡住", "拒绝转念"],
    meaningUpright: "倒吊人不是失败，而是主动停住，等待认知翻面。眼下最重要的不是快，而是看清。",
    meaningReversed: "逆位说明你可能拖太久，把暂停变成停滞，或为了维持现状不断牺牲自己。",
    loveMeaning: "感情里它提醒不要急着定义关系，先看彼此真实需求。",
    careerMeaning: "事业上适合观察、改策略、延后决策，而非勉强推进。",
  },
  {
    id: "major-13-death",
    nameZh: "死神",
    nameEn: "Death",
    arcana: "major",
    suit: null,
    number: 13,
    keywordsUpright: ["结束", "蜕变", "更新", "断舍离"],
    keywordsReversed: ["拖延结束", "依附过去", "僵局", "迟迟不转身"],
    meaningUpright: "死神是阶段终结与更新，不等于灾难，而是旧模式走到尽头，必须腾出空间。",
    meaningReversed: "逆位往往表示你明知该结束，却仍紧抓旧人旧事，导致更深的消耗。",
    loveMeaning: "关系里可能是旧阶段结束、关系重组，或不得不面对真相。",
    careerMeaning: "工作上象征岗位变化、项目终止、战略重启与必要清理。",
  },
  {
    id: "major-14-temperance",
    nameZh: "节制",
    nameEn: "Temperance",
    arcana: "major",
    suit: null,
    number: 14,
    keywordsUpright: ["调和", "节奏", "整合", "稳定恢复"],
    keywordsReversed: ["失衡", "走极端", "节奏混乱", "内耗"],
    meaningUpright: "节制强调把不同资源、情绪和需求重新调配，让局势回到可持续的节奏。",
    meaningReversed: "逆位意味着你可能在两个极端间来回摆动，缺少稳定的中间值。",
    loveMeaning: "感情里它是修复、慢慢靠近与彼此磨合的好牌。",
    careerMeaning: "事业上适合跨团队协作、流程优化与长期稳定推进。",
  },
  {
    id: "major-15-devil",
    nameZh: "恶魔",
    nameEn: "The Devil",
    arcana: "major",
    suit: null,
    number: 15,
    keywordsUpright: ["执念", "诱惑", "束缚", "依赖"],
    keywordsReversed: ["松绑", "看清控制", "脱离上瘾", "重获选择"],
    meaningUpright: "恶魔指出你被什么绑定住了，可能是欲望、恐惧、关系依赖或熟悉的自我限制。",
    meaningReversed: "逆位常见于意识到问题、准备戒断或开始退出不健康循环。",
    loveMeaning: "感情里涉及强烈吸引、控制、拉扯与情绪依附，需要边界。",
    careerMeaning: "工作上可能是金钱诱惑、过劳循环或不健康竞争环境。",
  },
  {
    id: "major-16-tower",
    nameZh: "高塔",
    nameEn: "The Tower",
    arcana: "major",
    suit: null,
    number: 16,
    keywordsUpright: ["震荡", "真相揭露", "崩解", "重建"],
    keywordsReversed: ["延后爆发", "内在崩塌", "勉强维持", "避而不见"],
    meaningUpright: "高塔让虚假稳定被打破。短期会不舒服，但它通常是必要清场，迫使你面对真相。",
    meaningReversed: "逆位表示外在还没完全倒，但内在早已知道旧结构撑不住了。",
    loveMeaning: "关系里它意味着重大真相出现、旧模式崩塌或关系急剧重组。",
    careerMeaning: "事业上常见于组织变动、计划中断、旧策略失灵，需要迅速重建。",
  },
  {
    id: "major-17-star",
    nameZh: "星星",
    nameEn: "The Star",
    arcana: "major",
    suit: null,
    number: 17,
    keywordsUpright: ["希望", "疗愈", "诚实", "愿景"],
    keywordsReversed: ["失去信心", "理想断线", "怀疑", "能量低迷"],
    meaningUpright: "星星带来柔和而坚定的希望，提醒你在诚实面对自己后，未来仍有光。",
    meaningReversed: "逆位表示你正在失去信任感，需要先修复内在，再谈远方目标。",
    loveMeaning: "感情里象征坦诚、疗愈与关系中的真诚愿景。",
    careerMeaning: "工作上有利于长线规划、品牌表达与找回初心。",
  },
  {
    id: "major-18-moon",
    nameZh: "月亮",
    nameEn: "The Moon",
    arcana: "major",
    suit: null,
    number: 18,
    keywordsUpright: ["不确定", "潜意识", "迷雾", "敏感"],
    keywordsReversed: ["看清幻象", "情绪澄清", "谣言消散", "回到事实"],
    meaningUpright: "月亮说明事情仍处在模糊期，情绪、恐惧和投射比事实更响亮，宜慢看。",
    meaningReversed: "逆位表示迷雾开始散去，你会逐步看见真相，但过程仍需谨慎。",
    loveMeaning: "关系里要警惕幻想、猜测与情绪投射，适合延后下定义。",
    careerMeaning: "工作上适合查证信息，避免在不透明条件下做重大承诺。",
  },
  {
    id: "major-19-sun",
    nameZh: "太阳",
    nameEn: "The Sun",
    arcana: "major",
    suit: null,
    number: 19,
    keywordsUpright: ["清晰", "生命力", "成功", "坦荡"],
    keywordsReversed: ["过度乐观", "迟来的明朗", "能量外泄", "高估局势"],
    meaningUpright: "太阳带来清晰、生命力和正面推进。事情开始变得坦率、可见、可确认。",
    meaningReversed: "逆位不一定差，更多是提醒你别因为短期顺风就忽略隐藏成本。",
    loveMeaning: "感情里象征真诚、公开、温暖与更有把握的发展。",
    careerMeaning: "事业上有利于曝光、发布、面试、合作推进与结果确认。",
  },
  {
    id: "major-20-judgement",
    nameZh: "审判",
    nameEn: "Judgement",
    arcana: "major",
    suit: null,
    number: 20,
    keywordsUpright: ["觉醒", "复盘", "召唤", "第二次机会"],
    keywordsReversed: ["拖延回应", "自责", "拒绝成长", "旧账缠身"],
    meaningUpright: "审判要求你认真回望过去，从旧经验里做出成熟回应，进入新的层次。",
    meaningReversed: "逆位提示你可能知道该改变，却仍停留在自责或逃避里。",
    loveMeaning: "关系里它意味着旧问题重提、复合议题，或一次必须诚实面对的清算。",
    careerMeaning: "事业上是复盘、转型和使命感被重新点亮的信号。",
  },
  {
    id: "major-21-world",
    nameZh: "世界",
    nameEn: "The World",
    arcana: "major",
    suit: null,
    number: 21,
    keywordsUpright: ["完成", "整合", "成熟", "阶段圆满"],
    keywordsReversed: ["未完待续", "收尾拖延", "闭环不足", "难以放下"],
    meaningUpright: "世界代表一个周期圆满结束，你已经把经验整合成更成熟的自己。",
    meaningReversed: "逆位通常是差最后一步，提醒你别在收尾阶段松散或回头重复旧模式。",
    loveMeaning: "感情里可能是关系成熟定型，或终于完成一段课题。",
    careerMeaning: "工作上对应项目完成、长期目标达成与更大舞台的开启。",
  },
];

export const tarotCards: TarotCard[] = [
  ...majorArcanaSeeds.map((card) => {
    const slug = slugify(card.nameEn);
    return {
      ...card,
      slug,
      imageUrl: `/tarot/${slug}.jpg`,
    };
  }),
  ...minorArcana.map((card) => ({
    ...card,
    imageUrl: `/tarot/${card.slug}.jpg`,
  })),
];
